MovieNight/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace MovieNight.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MovieNight/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieNight_BusinessLogic.Services;
using MovieNight_InterfacesLL.IServices;
using MovieNight_Classes;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Diagnostics.Eventing.Reader;
using Microsoft.TeamFoundation.TestManagement.WebApi;
using MovieNight_DataAccess.Controllers;

namespace MovieNight.Pages
{
    public class IndexModel : PageModel
    {
        public List<Movie> LatestMovies { get; set; }
        public List<Series> LatestSeries { get; set; }
        public User LoggedInUser { get; set; }


        private readonly IUserManager userManager;
        private readonly IMovieManager movieManager;
        private readonly ISeriesManager seriesManager;

        public IndexModel(IUserManager _userManager, IMovieManager _movieManager, ISeriesManager _seriesManager)
        {
            userManager = _userManager;
            movieManager = _movieManager;
            seriesManager = _seriesManager;
        }

        public void OnGet()
        {
            //Checks whether anyone is logged in
            if (User.FindFirst("id") != null)
            {
                try
                {
                    LoggedInUser = userManager.GetUserById(int.Parse(User.FindFirst("id").Value));
                    if (IsBanned(LoggedInUser))
                    {
                        RedirectToPage("/Account/Logout");
                    }
                }
                catch (ArgumentException ex)
                {
                    ViewData["Error"] = ex.Message;
                }
            }

            LatestMovies = movieManager.Get7();
            LatestSeries = seriesManager.Get7();
        }
        public bool IsBanned(User user)
        {
            if (userManager.BannedUser(user) == true)
            {
                return true;
            }
            return false;
        }
    }
}

MovieNight/Pages/Movies.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieNight_BusinessLogic.Services;
using MovieNight_Classes;
using MovieNight_DataAccess.Controllers;
using MovieNight_InterfacesLL.IServices;
using System.Diagnostics;
using System.Security.Claims;

namespace MovieNight.Pages
{
    public class MoviePageModel : PageModel
    {
        public Movie Movie { get; set; }
        public List<Comments> Comments { get; set; }
        [BindProperty]
        public string CommentLeft { get; set; }
        public User LoggedInUser { get; set; }
        public int UserId { get; set; }
        public string WatchLaterButtonText => IsInWatchLater ? "Added to Watch Later" : "Add to Watch Later";
        public bool IsInWatchLater { get; private set; }
        public string WatchingButtonText => IsInWatching ? "Added to Currently Watching" : "Add to Currently Watching";
        public bool IsInWatching { get; private set; }
        public string FinishedButtonText => IsInFinished ? "Added to Finished" : "Add to Finished";
        public bool IsInFinished { get; private set; }
        public string FavouritesButtonText => IsInFavourites ? "Liked ❤" : "Like ❤";
        public bool IsInFavourites { get; private set; }
        public bool IsRated { get; private set; }
        public int MovieRates { get; set; }
        public int MovieRating { get; set; }


        private readonly IMovieManager movieManager;
        private readonly ICommentManager commentManager;
        private readonly IUserManager userManager;
        private readonly IWatchLaterManager watchLaterManager;
        private readonly IWatchingManager watchingManager;
        private readonly IFinishedManager finishedManager;
        private readonly IFavouritesManager favouritesManager;
        private readonly IRatingManager ratingManager;

        public MoviePageModel(IMovieManager _movieManager, ICommentManager _commentManager, IUserManager _userManager, IWatchLaterManager _watchLaterManager, IWatchingManager _watchingManager, IFinishedManager _finishedManager, IFavouritesManager _favouritesManager, IRatingManager _ratingManager)
        {
            movieManager = _movieManager;
            commentManager = _commentManager;
            userManager = _userManager;
            watchLaterManager = _watchLaterManager;
            watchingManager = _watchingManager;
            finishedManager = _finishedManager;
            favouritesManager = _favouritesManager;
            ratingManager = _ratingManager;
        }
        public void OnGet(int id)
        {
            Movie = movieManager.GetById(id);
            Comments = commentManager.GetAll(Movie.Id);
            if (User.FindFirst("id") != null)
            {
                LoggedInUser = userManager.GetUserById(int.Parse(User.FindFirst("id").Value));
                UserId = LoggedInUser.Id;
                IsInWatchLater = watchLaterManager.CheckFolder(Movie.Id, UserId);
                IsInWatching = watchingManager.CheckFolder(Movie.Id, UserId);
                IsInFinished = finishedManager.CheckFolder(Movie.Id, UserId);
                IsInFavourites = favouritesManager.CheckFolder(Movie.Id, UserId);
                IsRated = ratingManager.CheckRate(Movie.Id, UserId);
                MovieRates = ratingManager.GetCount(Movie.Id);
                MovieRating = ratingManager.GetAvgRate(Movie.Id);

                if (IsRated)
                {
                    Rating currentRating = ratingManager.GetRate(Movie.Id, UserId);
                    if (currentRating.Rate == 1) { currentRating.Rate = 5; }
                    else if (currentRating.Rate == 2) { currentRating.Rate = 4; }
                    else if (currentRating.Rate == 4) { currentRating.Rate = 2; }
                    else if (currentRating.Rate == 5) { currentRating.Rate = 1; }
                    ViewData["UserRating"] = currentRating.Rate;
                }
                if (IsBanned(LoggedInUser))
                {
                    RedirectToPage("/Account/Logout");
                }
            }
            foreach (var comment in Comments)
            {
                comment.Username = userManager.GetUserById(comment.UserId).Username;
            }
        }
        public bool IsBanned(User user)
        {
            if (userManager.BannedUser(user) == true)
            {
                return true;
            }
            return false;
        }
        public IActionResult OnPostComment(int id)
        {
            //Checks whether anyone is logged inm
            if (User.FindFirst("id") != null)
            {
                try
                {
                    UserId = int.Parse(User.FindFirst("id").Value);
                    commentManager.PostComment(new Comments(0, UserId, id, DateTime.Now, CommentLeft));

                    CommentLeft = ""; // Reset the comment box

                    // Re-fetch movie data and other necessary data
                    Movie = movieManager.GetById(id);
                    Comments = commentManager.GetAll(id);

                    return RedirectToPage(new { id = id });
                }
                catch (Exception ex)
                {
                    ViewData["Error"] = ex.Message;
                    return RedirectToPage(new { id = id });
                }
            }
            else
            {
                return RedirectToPage("/Account/Login");
            }
        }

        public bool CanDeleteComment(int id)
        {
            //Checks whether anyone is logged in
            if (User.FindFirst("id") != null)
            {
                try
                {
                    UserId = int.Parse(User.FindFirst("id").Value);
                    if (userManager.GetUserById(UserId).Id == id || userManager.GetUserById(UserId).Role == "admin")
                    {
                        return true;
                    }
                    else
                    {
                        return false;
                    }
                }
                catch (Exception ex)
                {
                    Debug.WriteLine(ex);
                    return false;
                }
            }
            return false;
        }
        public IActionResult OnPostDeleteComment(int id, int commentId)
        {
            try
            {
                // Authorization check: Ensure the user is allowed to delete the comment
                var comment = commentManager.GetById(commentId);
                if (comment != null && CanDeleteComment(comment.UserId))
                {
                    commentManager.DelComment(commentId);

                    // Re-fetch movie data and other necessary data
                    Movie = movieManager.GetById(id);
                    Comments = commentManager.GetAll(id);

                    return RedirectToPage(new { id = id });
                }

                // If the user is not authorized to delete, handle accordingly
                // Redirect to the same page with an error message or a status
                TempData["ErrorMessage"] = "You are not authorized to delete this comment.";

                Movie = movieManager.GetById(id);
                Comments = commentManager.GetAll(id);

                return RedirectToPage(new { id = id });
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
                Movie = movieManager.GetById(id);
                Comments = commentManager.GetAll(id);
                return RedirectToPage(new { id = id });
            }
        }
        public IActionResult OnPostToggleWatchLater(int movieId)
        {
            try
            {
                if (User.FindFirst("id") != null)
                {
                    UserId = int.Parse(User.FindFirst("id").Value);
                    IsInWatchLater = watchLaterManager.CheckFolder(movieId, UserId);
                    if (IsInWatchLater)
                    {
                        watchLaterManager.RemoveFrom(new Folderkeep(movieId, UserId, 0, DateTime.Now));
                    }
                    else
                    {
                        watchLaterManager.AddTo(new Folderkeep(movieId, UserId, 0, DateTime.Now));
                    }
                    IsInWatchLater = !IsInWatchLater;
                    // Re-fetch movie data and other necessary data
                    Movie = movieManager.GetById(movieId);
                    Comments = commentManager.GetAll(movieId);
                    return RedirectToPage(new { id = movieId });
                }
                else
                {
                    return RedirectToPage("/Account/Login");
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
                Movie = movieManager.GetById(movieId);
                Comments = commentManager.GetAll(movieId);
                return RedirectToPage(new { id = movieId });
            }
        }

        public IActionResult OnPostToggleWatching(int movieId)
        {
            try
            {
                if (User.FindFirst("id") != null)
                {
                    UserId = int.Parse(User.FindFirst("id").Value);
                    IsInWatching = watchingManager.CheckFolder(movieId, UserId);
                    if (IsInWatching)
                    {
                        watchingManager.RemoveFrom(new Folderkeep(movieId, UserId, 0, DateTime.Now));
                    }
                    else
                    {
                        watchingManager.AddTo(new Folderkeep(movieId, UserId, 0, DateTime.Now));
                    }
                    IsInWatching = !IsInWatching;
                    // Re-fetch movie data and other necessary data
                    Movie = movieManager.GetById(movieId);

MovieNight/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MovieNight.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

MovieNight/Pages/Register.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MovieNight.Pages
{
    public class RegisterModel : PageModel
    {
        public void OnGet()
        {
            
        }
    }
}

MovieNight/Pages/SearchResults.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieNight_BusinessLogic.Services;
using MovieNight_Classes;
using MovieNight_DataAccess.Controllers;
using MovieNight_InterfacesLL.IServices;
using System.Runtime.ExceptionServices;

namespace MovieNight.Pages
{
    public class SearchResultsModel : PageModel
    {
        public User LoggedInUser { get; set; }
        public List<User> UserResults { get; set; }
        public List<Movie> MovieResults { get; set; }
        public List<Series> SeriesResults { get; set; }

        private readonly IUserManager userManager;
        private readonly IMovieManager movieManager;
        private readonly ISeriesManager seriesManager;
        
        public SearchResultsModel(IUserManager _userManager, IMovieManager _movieManager, ISeriesManager _seriesManager)
        {
            userManager = _userManager;
            movieManager = _movieManager;
            seriesManager = _seriesManager;
        }
        public void OnGet(string search)
        {
            UserResults = userManager.Search(search);
            MovieResults = movieManager.Search(search);
            SeriesResults = seriesManager.Search(search);

            if (User.FindFirst("id") != null)
            {
                try
                {
                    LoggedInUser = userManager.GetUserById(int.Parse(User.FindFirst("id").Value));
                    if (IsBanned(LoggedInUser))
                    {
                        RedirectToPage("/Account/Logout");
                    }
                }
                catch (ArgumentException ex)
                {
                    ViewData["Error"] = ex.Message;
                }
            }
        }

        public bool IsBanned(User user)
        {
            if (userManager.BannedUser(user) == true)
            {
                return true;
            }
            return false;
        }
    }
}

MovieNight/Pages/ToS.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieNight_BusinessLogic.Services;
using MovieNight_Classes;
using MovieNight_DataAccess.Controllers;
using MovieNight_InterfacesLL.IServices;

namespace MovieNight.Pages
{
    public class ToSModel : PageModel
    {
        public User LoggedInUser { get; set; }

        private readonly IUserManager userManager;
        public ToSModel(IUserManager _userManager) 
        {
            userManager = _userManager;
        }
        public void OnGet()
        {
            if (User.FindFirst("id") != null)
            {
                try
                {
                    LoggedInUser = userManager.GetUserById(int.Parse(User.FindFirst("id").Value));
                    if (IsBanned(LoggedInUser))
                    {
                        HttpContext.SignOutAsync();
                    }
                }
                catch (ArgumentException ex)
                {
                    ViewData["Error"] = ex.Message;
                }
            }
        }

        public bool IsBanned(User user)
        {
            if (userManager.BannedUser(user) == true)
            {
                return true;
            }
            return false;
        }
    }
}

MovieNight/Pages/Index.cshtml
@page
@model IndexModel
@{
    @if (Model.LoggedInUser != null)
    {
        Layout = "_LayoutLoggedIn";
    }
    ViewData["Title"] = "Home page";
}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/IndexPage.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-4">
        <h2 class="textborderstyle text-white mb-3">Latest Added Movies</h2>
        <div class="row">
            @foreach (var movie in Model.LatestMovies)
            {
                <div class="col-md-6 col-lg-4 col-xl-3 mb-4">
                    <a href="/Movies/@movie.Id" class="text-decoration-none">
                        <div class="card bg-dark text-white movie-item h-100">
                            <img src="@movie.ImageLink" class="card-img-top img-fluid" alt="@movie.Title" style="height: 300px; object-fit: cover;">
                            <div class="card-body">
                                <p class="card-title text-truncate">@movie.Title</p>
                            </div>
                        </div>
                    </a>
                </div>
            }
        </div>
        <h2 class="textborderstyle text-white mb-3">Latest Added Series</h2>
        <div class="row">
            @foreach (var series in Model.LatestSeries)
            {
                <div class="col-md-6 col-lg-4 col-xl-3 mb-4">
                    <a href="/Series/@series.Id" class="text-decoration-none">
                        <div class="card bg-dark text-white movie-item h-100">
                            <img src="@series.ImageLink" class="card-img-top img-fluid" alt="@series.Title" style="height: 300px; object-fit: cover;">
                            <div class="card-body">
                                <p class="card-title text-truncate">@series.Title</p>
                            </div>
                        </div>
                    </a>
                </div>
            }
        </div>
    </div>
</body>

MovieNight/Pages/MoviePage.cshtml
@page "{id:int}"
@model MovieNight.Pages.MoviePageModel
@{
}

@* <a asp-page="/MoviePage" asp-route-id="@Model.Movie.Id"></a> *@

<head>
    <meta charset="UTF-8">
    <title>@Model.Movie.Title</title>
    <link rel="stylesheet" href="/css/MoviePage.css">
</head>
<body>
    <div class="movie-page">
        <header class="movie-header">
            <div class="header-content">
                <h1 class="movie-title">@Model.Movie.Title</h1>
                <div class="movie-subtitle">
                    <span class="original-title">Original title: @Model.Movie.Title |</span>
                    <span class="bubble">@Model.Movie.Year</span>
                    <span class="bubble">PG-13</span>
                    <span class="bubble">@Model.Movie.Length min</span>
                </div>
            </div>
        </header>

        <main class="movie-main">
            <div class="media-container">
                <div class="poster-container">
                    <img src="@Model.Movie.ImageLink" alt="@Model.Movie.Title" class="movie-poster">
                </div>
                <div class="trailer-container">
                    <iframe class="movie-trailer" src="@Model.Movie.TrailerLink" title="@Model.Movie.Title"
                             frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
                    </iframe>
                </div>
            </div>
        </main>

        <aside class="movie-sidebar">
            <div class="movie-content">
                <div class="movie-description-and-actions">
                    <div class="movie-description">
                        <p>@Model.Movie.Description</p>
                    </div>
                    <div class="movie-actions">
                        <button class="button rate-button">Rate</button>
                        <button class="button watchlist-button">+ Add to Watchlist</button>
                    </div>
                </div>
                <div class="movie-details">
                    <div class="movie-detail">Director: Nicolas Winding Refn</div>
                    <div class="movie-detail">Country: @Model.Movie.Country</div>
                    <div class="movie-detail">Category: @Model.Movie.Category</div>
                    <div class="movie-detail">Year: @Model.Movie.Year</div>
                </div>
            </div>
            <div class="comment-section">
                <h3>Comments</h3>
                <form method="post" asp-page-handler="Comment">
                    <textarea asp-for="CommentLeft" placeholder="Leave a comment... "></textarea>
                    <input type="submit" value="Post Comment"/>
                </form>

                <!-- Display comments -->
                @foreach (var comment in Model.Comments)
                {
                    <div class="comment">
                        <div class="comment-header">
                            <a href="" class="comment-user">@comment.Username</a>
                            <span class="comment-date">@comment.CommentDate.ToString("dd/MM/yyyy")</span>
                        </div>
                        <div class="comment-body">@comment.Information</div>
                        @if (Model.CanDeleteComment(comment.UserId))
                        {
                            <form method="post" asp-page-handler="DeleteComment" asp-route-id="@Model.Movie.Id" asp-route-commentId="@comment.Id">
                                <button type="submit" class="delete-comment-button" title="Delete">
                                    &#x1F5D1; <!-- Unicode for trash bin -->
                                </button>
                            </form>
                        }
                    </div>
                }
            </div>
            <!-- Additional sidebar sections like awards, box office, etc. -->
        </aside>
    </div>
    <script src="/js/MoviePage.js"></script>
</body>

MovieNight/Pages/Movies.cshtml
@page "{id:int}"
@model MovieNight.Pages.MoviePageModel
@{
    @if (Model.LoggedInUser != null)
    {
        Layout = "_LayoutLoggedIn";
    }
    ViewData["Title"] = Model.Movie.Title;
}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/MoviePage.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
</head>
<body>
    <div class="movie-page">
        <div class="movie-header">
            <div class="header-content">
                <h1 class="movie-title">@Model.Movie.Title</h1>
                <div class="movie-subtitle">
                    <span class="original-title">Original title: @Model.Movie.Title   |</span>
                    <span class="bubble">@Model.Movie.Year</span>
                    <span class="bubble">Movie</span>
                    <span class="bubble">@Model.Movie.Length min</span>
                </div>
            </div>
        </div>

        <main class="movie-main">
            <div class="container-fluid p-0">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <div class="poster-container">
                            <img src="@Model.Movie.ImageLink" alt="@Model.Movie.Title" class="movie-poster">
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="trailer-container">
                            <iframe class="movie-trailer" src="@Model.Movie.TrailerLink" title="@Model.Movie.Title"
                                    frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
                            </iframe>
                        </div>
                    </div>
                </div>
            </div>
        </main>

        <aside class="movie-sidebar">
            <div class="movie-content">
                <div class="movie-description-and-actions">
                    <div class="movie-description">
                        <p>@Model.Movie.Description</p>
                        <div class="movie-details">
                            <div class="movie-detail">Director: @Model.Movie.Director</div>
                            <div class="movie-detail">
                                Rating: @if (Model.MovieRating == 0)
                                {
                                    @:No rating yet
                                }
                                else
                                {
                                    @:@Model.MovieRating/5
                                }@if (Model.MovieRates == 1)
                                {
                                    @:(@Model.MovieRates vote)
                                }
                                else if(Model.MovieRates != 0)
                                {
                                    @:(@Model.MovieRates votes)
                                }
                            </div>
                            <div class="movie-detail">Country: @Model.Movie.Country</div>
                            <div class="movie-detail">Category: @Model.Movie.Category</div>
                            <div class="movie-detail">Year: @Model.Movie.Year</div>
                        </div>
                    </div>
                    <div class="movie-actions">
                        <div class="row">
                            <div class="col-sm-7">
                                <!-- Star Rating System -->
                                <div class="rate-label">Your Rating:</div>
                                <form method="post" asp-page-handler="Rate" asp-route-movieId="@Model.Movie.Id" id="ratingForm">
                                    <div class="rating">
                                        @for (int i = 1; i <= 5; i++)
                                        {
                                            <input type='radio' hidden name='rating' id='rating_@i' value="@i"
                                            @(ViewData["UserRating"] as int? == i ? "checked" : "")
                                                   onclick="document.getElementById('ratingForm').submit();">
                                            <label for='rating_@i'></label>
                                        }
                                    </div>
                                </form>
                                @if (Model.IsRated)
                                {
                                    <form method="post" asp-page-handler="DeleteRate" asp-route-movieId="@Model.Movie.Id">
                                        <button type="submit" title="Delete" class="delete-rating-button">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </form>
                                }
                            </div>
                            <div class="col-sm-4">
                                <!-- Favourites Button -->
                                <form method="post" asp-page-handler="ToggleFavourites" asp-route-movieId="@Model.Movie.Id">
                                    <input type="hidden" name="movieId" value="@Model.Movie.Id" />
                                    <button type="submit" class="button watchlist-button">
                                        @Model.FavouritesButtonText
                                    </button>
                                </form>
                            </div>
                        </div>
                        <!-- Watchlist Button -->
                        <form method="post" asp-page-handler="ToggleWatchLater" asp-route-movieId="@Model.Movie.Id">
                            <input type="hidden" name="movieId" value="@Model.Movie.Id" />
                            <button type="submit" class="button watchlist-button">
                                @Model.WatchLaterButtonText
                            </button>
                        </form>
                        <form method="post" asp-page-handler="ToggleWatching" asp-route-movieId="@Model.Movie.Id">
                            <input type="hidden" name="movieId" value="@Model.Movie.Id" />
                            <button type="submit" class="button currently-watching-button">
                                @Model.WatchingButtonText
                            </button>
                        </form>
                        <form method="post" asp-page-handler="ToggleFinished" asp-route-movieId="@Model.Movie.Id">
                            <input type="hidden" name="movieId" value="@Model.Movie.Id" />
                            <button type="submit" class="button finished-button">
                                @Model.FinishedButtonText
                            </button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="comment-section">
                <h3>Comments</h3>
                <form method="post" asp-page-handler="Comment" asp-route-movieId="@Model.Movie.Id">
                    <textarea asp-for="CommentLeft" placeholder="Leave a comment... "></textarea>
                    <input type="submit" value="Post Comment" class="button comment-button" style="background-color: rgb(117, 54, 112); color: white;"/>
                </form>

                <!-- Display comments -->
                @foreach (var comment in Model.Comments)
                {
                    <div class="comment">
                        <div class="comment-header">
                            <a href="" class="comment-user">@comment.Username</a>
                            <span class="comment-date">@comment.CommentDate.ToString("dd/MM/yyyy")</span>
                        </div>
                        <div class="comment-body">@comment.Information</div>
                        @if (Model.CanDeleteComment(comment.UserId))
                        {
                            <form method="post" asp-page-handler="DeleteComment" asp-route-id="@Model.Movie.Id" asp-route-commentId="@comment.Id">
                                <button type="submit" class="delete-comment-button" title="Delete">
                                    &#x1F5D1; <!-- Unicode for trash bin -->
                                </button>
                            </form>
                        }
                    </div>
                }
            </div>
        </aside>
    </div>
</body>